---
# tasks file for hoplacloud.letsencrypt

- name: Install Certbot (letsencrypt) PPA Repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
  when: "'bionic' in ansible_distribution_release"

- name: Install Certbot for {{ server_type }} web server
  apt:
    name: python-certbot-{{ server_type }}
    state: latest
    update_cache: yes
  when: "'bionic' in ansible_distribution_release"

- name: Install Certbot for {{ server_type }} web server
  apt:
    name: python3-certbot-{{ server_type }}
    state: latest
    update_cache: yes
  when: "'focal' in ansible_distribution_release"
